Routing algorithm overhaul
simgrid/simgrid pull request #401
Opened 2024-12-20 12:32 UTC by JRodez

Clean rebase of #392 which fixes #389.
Maybe it would be nice having more tests. 
Also we can add a fix to #400 in this MR if needed.

Have a nice day.
JR

2024-12-20 12:33 UTC, JRodez commented
Note that I have removed the macros defined in [d4630dc](https://github.com/simgrid/simgrid/pull/401/commits/d4630dc6bfa111ccf2fce573fe7a11b50f1449aa) to definitively replace the base algorithm.

2024-12-23 16:06 UTC, frs69wq requested changes
Thanks for this PR, really helpful. I left a few comments along the way.
A few files are only modified because of clang-format, maybe these modifications could be committed outside of the PR.

2024-12-23 16:06 UTC, frs69wq commented on src/kernel/routing/NetZoneImpl.cpp
> +/* Compute the route between a leaf NetPoint and an upper router */
I have a hard time visualizing where in the hierarchy is that function used. Maybe an illustration or a more detailed comment would help.

2024-12-23 16:06 UTC, frs69wq commented on src/kernel/routing/NetZoneImpl.cpp
> +  xbt_enforce(gateways_.size() < 2, "NetZone '%s' has more than one gateway, please provide a gateway name",
provide a "unique" gateway name, maybe.

2025-01-10 12:56 UTC, JRodez commented
> Thanks for this PR, really helpful. I left a few comments along the way. A few files are only modified because of clang-format, maybe these modifications could be committed outside of the PR.

Hello, thanks for your comments.

> A few files are only modified because of clang-format, maybe these modifications could be committed outside of the PR.

Which commits are you talking about?

2025-01-10 13:05 UTC, JRodez commented on src/kernel/routing/NetZoneImpl.cpp
> +      path_src->erase(path_src->begin(), src_it + 2);
Maybe instead of modifying the vectors directly, it would be better to do it a posteriori using 2 index.

2025-01-10 13:25 UTC, frs69wq commented
> > A few files are only modified because of clang-format, maybe these modifications could be committed outside of the PR.

> Which commits are you referring to exactly?

I wasn't referring to a specific commit, but I saw some modifications along the way while reviewing the PR that clearly come from clang-format. Not your fault, more likely that of some of us (tipically me ;)) who didn't apply clang-format when committing. Not a big deal, it made it just a tiny bit harder to identify the more important changes. Not critical at all though.

2025-01-10 13:26 UTC, frs69wq commented on src/kernel/routing/NetZoneImpl.cpp
> +      path_src->erase(path_src->begin(), src_it + 2);
just explaining in comments what is done here and why can be enough IMHO

2025-03-25 19:25 UTC, JRodez commented on src/kernel/routing/NetZoneImpl.cpp
> +/* Compute the route between a leaf NetPoint and an upper router */
I think this is clear enough now, what do you think ?

2025-03-25 19:32 UTC, JRodez commented
I rewrote a large part of the code to make it more understandable.
I have trouble simplifying more.

Note : We should reverse `xxx_path` vectors for using `.erase()` in a more efficient way.

2025-03-27 14:36 UTC, frs69wq commented on src/kernel/routing/NetZoneImpl.cpp
> +/* Compute the route between a leaf NetPoint and an upper router */
Looks good like this

2025-03-27 14:45 UTC, frs69wq approved these changes
Changes look great.

About the note on reversing the paths to optimize the erase operations, I'm not sure it's critical. I'm not expecting to see platforms nesting more than a few zones (10 is already more than what I can imagine).

2025-03-27 14:45 UTC, merged